services:
  - type: web
    name: rayyon-restoran
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11.0"
